kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    description: Defines how to build the application
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.source_repository_url | quote }}
      ref: {{ .Values.source_repository_ref | quote }}
    contextDir: {{ .Values.context_dir | quote }}
    {{ if .Values.scmsecret }}
    sourceSecret:
      name: {{ .Values.scmsecret | quote }}
    {{ end }}
  strategy:
    type: Source
    sourceStrategy:
      incremental : true
      from:
        kind: ImageStreamTag
        namespace: {{ .Release.Namespace | quote }}
        name: {{ print .Values.s2iimage ":latest" | quote }}
      {{- if .Values.pullSecret }}
      pullSecret:
        name: {{ .Values.pullSecret | quote }}
      {{- end }}  
      {{- if .Values.build_env }}
      env:
        {{- range .Values.build_env }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
      {{- end }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ print .Values.name ":latest" | quote }}
  triggers:
  - type: ImageChange
  - type: ConfigChange
  {{ if .Values.webhookSecrets }}
  - type: GitHub
    github:
      secret: {{ .Values.github_webhook_secret | default (randAlphaNum 40) | quote }}
  - type: Generic
    generic:
      secret: {{ .Values.generic_webhook_secret | default (randAlphaNum 40) | quote }}
  {{ end }}
  {{ if .Values.memory_limit }}
  resources:
    limits:
      memory: {{ .Values.memory_limit }}
  {{ end }}